CREATE TABLE IF NOT EXISTS Users (
	id VARCHAR(20) NOT NULL,
  	username VARCHAR(50) NOT NULL,
  	password VARCHAR(255) NOT NULL,
  	email VARCHAR(100) NOT NULL,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    phoneNo VARCHAR(100) NOT NULL,
    isAdmin BOOLEAN NOT NULL DEFAULT 0,

    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS Stadiums (
	id VARCHAR(20) NOT NULL,
  	location VARCHAR(50) NOT NULL,
  	stadiumName VARCHAR(100) NOT NULL,
  	noOfSeats VARCHAR(20) NOT NULL,

    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS Teams (
	id VARCHAR(20) NOT NULL,
  	teamName VARCHAR(50) NOT NULL,
  	stadiumID VARCHAR(20) NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (stadiumID) REFERENCES Stadiums(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS Matches (
	id VARCHAR(20) NOT NULL,
	opponent VARCHAR(20) NOT NULL,
  	matchDate DATE NOT NULL,
	price INT NOT NULL,
  	matchType INT NOT NULL DEFAULT 0,
    isHome BOOLEAN NOT NULL DEFAULT 0,

    PRIMARY KEY (id),
	FOREIGN KEY (opponent) REFERENCES Teams(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS Tickets (
	id VARCHAR(20) NOT NULL,
  	matchID VARCHAR(20) NOT NULL,
  	userID VARCHAR(20),
	orderID VARCHAR(20) NOT NULL,
  	seatingPosition TINYINT(1) NOT NULL,
    
    PRIMARY KEY (id),
    FOREIGN KEY (matchID) REFERENCES Matches(id),
    FOREIGN KEY (userID) REFERENCES Users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS SeasonTickets (
	id VARCHAR(20) NOT NULL,
  	userID VARCHAR(20) NOT NULL,
  	seatingPosition VARCHAR(100) NOT NULL,
	price INT NOT NULL,
	
    PRIMARY KEY (id),
    FOREIGN KEY (userID) REFERENCES Users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS Orders (
	id VARCHAR(20) NOT NULL,
	fullName VARCHAR(200) NOT NULL,
	email VARCHAR(100) NOT NULL,
	address VARCHAR(200) NOT NULL,
	city VARCHAR(100) NOT NULL,
	state VARCHAR(100) NOT NULL,
	zip VARCHAR(100) NOT NULL,
	nameOnCard VARCHAR(100) NOT NULL,
	creditCardNumber INT(17) NOT NULL,
	expiryMonth VARCHAR(20) NOT NULL,
	expiryYear VARCHAR(4) NOT NULL,
	cvv VARCHAR(255) NOT NULL,
	totalCost DECIMAL(10,2) NOT NULL,

	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;