CREATE TABLE IF NOT EXISTS Users (
	id VARCHAR(20) NOT NULL,
  	username VARCHAR(50) NOT NULL,
  	password VARCHAR(255) NOT NULL,
  	email VARCHAR(100) NOT NULL,
	firstName VARCHAR(100) NOT NULL,
	lastName VARCHAR(100) NOT NULL,
	address VARCHAR(100) NOT NULL,
	phoneNo VARCHAR(100) NOT NULL,
	isAdmin BOOLEAN,

    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS Matches ( 
	id VARCHAR(20) NOT NULL,
	opponent VARCHAR(100) NOT NULL,
	matchDate VARCHAR(20) NOT NULL,
  	matchType VARCHAR(20) NOT NULL,
	isHome BOOLEAN,

    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS Stadiums (
	  id VARCHAR(20) NOT NULL,
  	location VARCHAR(50) NOT NULL,
  	stadiumName VARCHAR(100) NOT NULL,
  	noOfSeats VARCHAR(20) NOT NULL,

    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS Teams (
	  id VARCHAR(20) NOT NULL,
  	teamName VARCHAR(50) NOT NULL,
  	stadiumID VARCHAR(20) NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (stadiumID) REFERENCES Stadiums(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS Tickets (
	  id VARCHAR(20) NOT NULL,
  	matchID VARCHAR(20) NOT NULL,
  	userID VARCHAR(20) NOT NULL,
  	seatingPosition VARCHAR(100) NOT NULL,
    isSeason BOOLEAN,

    PRIMARY KEY (id),
    FOREIGN KEY (matchID) REFERENCES Matches(id),
    FOREIGN KEY (userID) REFERENCES Users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
